
package org.icatproject;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICAT", targetNamespace = "http://icatproject.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICAT {


    /**
     * 
     * @param sessionId
     * @param query
     * @param primaryKey
     * @return
     *     returns org.icatproject.EntityBaseBean
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://icatproject.org", className = "org.icatproject.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetResponse")
    public EntityBaseBean get(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "query", targetNamespace = "")
        String query,
        @WebParam(name = "primaryKey", targetNamespace = "")
        long primaryKey)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param bean
     * @param sessionId
     * @throws IcatException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://icatproject.org", className = "org.icatproject.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.DeleteResponse")
    public void delete(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "bean", targetNamespace = "")
        EntityBaseBean bean)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param query
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://icatproject.org", className = "org.icatproject.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.SearchResponse")
    public List<Object> search(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "query", targetNamespace = "")
        String query)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param bean
     * @param sessionId
     * @return
     *     returns long
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://icatproject.org", className = "org.icatproject.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.CreateResponse")
    public long create(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "bean", targetNamespace = "")
        EntityBaseBean bean)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param bean
     * @param sessionId
     * @throws IcatException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://icatproject.org", className = "org.icatproject.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.UpdateResponse")
    public void update(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "bean", targetNamespace = "")
        EntityBaseBean bean)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg23
     * @param arg0
     * @param arg22
     * @param arg21
     * @param arg20
     * @param arg27
     * @param arg26
     * @param arg25
     * @param arg24
     * @param arg29
     * @param arg28
     * @param arg30
     * @param arg32
     * @param arg31
     * @param arg19
     * @param arg17
     * @param arg18
     * @param arg15
     * @param arg16
     * @param arg13
     * @param arg14
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @RequestWrapper(localName = "dummy", targetNamespace = "http://icatproject.org", className = "org.icatproject.Dummy")
    @ResponseWrapper(localName = "dummyResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.DummyResponse")
    public void dummy(
        @WebParam(name = "arg0", targetNamespace = "")
        Datafile arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        DatafileFormat arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        DatafileParameter arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Dataset arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        DatasetParameter arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        DatasetType arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Facility arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        FacilityCycle arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        InstrumentScientist arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        User arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        Instrument arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        Investigation arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        InvestigationType arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        InvestigationUser arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        Keyword arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        ParameterType arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        Publication arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        RelatedDatafile arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        Sample arg18,
        @WebParam(name = "arg19", targetNamespace = "")
        SampleParameter arg19,
        @WebParam(name = "arg20", targetNamespace = "")
        Shift arg20,
        @WebParam(name = "arg21", targetNamespace = "")
        Study arg21,
        @WebParam(name = "arg22", targetNamespace = "")
        StudyInvestigation arg22,
        @WebParam(name = "arg23", targetNamespace = "")
        StudyStatus arg23,
        @WebParam(name = "arg24", targetNamespace = "")
        Application arg24,
        @WebParam(name = "arg25", targetNamespace = "")
        Job arg25,
        @WebParam(name = "arg26", targetNamespace = "")
        InputDataset arg26,
        @WebParam(name = "arg27", targetNamespace = "")
        OutputDataset arg27,
        @WebParam(name = "arg28", targetNamespace = "")
        InputDatafile arg28,
        @WebParam(name = "arg29", targetNamespace = "")
        OutputDatafile arg29,
        @WebParam(name = "arg30", targetNamespace = "")
        NotificationRequest arg30,
        @WebParam(name = "arg31", targetNamespace = "")
        Group arg31,
        @WebParam(name = "arg32", targetNamespace = "")
        UserGroup arg32);

    /**
     * 
     * @param sessionId
     * @throws IcatException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://icatproject.org", className = "org.icatproject.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.LogoutResponse")
    public void logout(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param credentials
     * @param plugin
     * @return
     *     returns java.lang.String
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://icatproject.org", className = "org.icatproject.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.LoginResponse")
    public String login(
        @WebParam(name = "plugin", targetNamespace = "")
        String plugin,
        @WebParam(name = "credentials", targetNamespace = "")
        org.icatproject.Login.Credentials credentials)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns java.lang.String
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetUserNameResponse")
    public String getUserName(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param beanName
     * @return
     *     returns org.icatproject.EntityInfo
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityInfo", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetEntityInfo")
    @ResponseWrapper(localName = "getEntityInfoResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetEntityInfoResponse")
    public EntityInfo getEntityInfo(
        @WebParam(name = "beanName", targetNamespace = "")
        String beanName)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param beans
     * @return
     *     returns java.util.List<java.lang.Long>
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMany", targetNamespace = "http://icatproject.org", className = "org.icatproject.CreateMany")
    @ResponseWrapper(localName = "createManyResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.CreateManyResponse")
    public List<Long> createMany(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "beans", targetNamespace = "")
        List<EntityBaseBean> beans)
        throws IcatException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.lang.String
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApiVersion", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetApiVersion")
    @ResponseWrapper(localName = "getApiVersionResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetApiVersionResponse")
    public String getApiVersion()
        throws IcatException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @return
     *     returns double
     * @throws IcatException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRemainingMinutes", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetRemainingMinutes")
    @ResponseWrapper(localName = "getRemainingMinutesResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.GetRemainingMinutesResponse")
    public double getRemainingMinutes(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId)
        throws IcatException_Exception
    ;

    /**
     * 
     * @param sessionId
     * @param beans
     * @throws IcatException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteMany", targetNamespace = "http://icatproject.org", className = "org.icatproject.DeleteMany")
    @ResponseWrapper(localName = "deleteManyResponse", targetNamespace = "http://icatproject.org", className = "org.icatproject.DeleteManyResponse")
    public void deleteMany(
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "beans", targetNamespace = "")
        List<EntityBaseBean> beans)
        throws IcatException_Exception
    ;

}
