
package org.icatproject;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "IcatException", targetNamespace = "http://icatproject.org")
public class IcatException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IcatException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IcatException_Exception(String message, IcatException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IcatException_Exception(String message, IcatException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.icatproject.IcatException
     */
    public IcatException getFaultInfo() {
        return faultInfo;
    }

}
