connect 'jdbc:derby://localhost:1527/icatuser;Password=APP:User=APP';
INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('guest', 'password');
INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('reader', 'password');
INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('CIC', 'password');
INSERT INTO PASSWD (USERNAME, ENCODEDPASSWORD) VALUES ('root', 'password');

