#!/bin/bash
#
# $Id$
#

# load user details
. ./vars

mysql -u$DB_USERNAME -p$DB_PASSWORD <<EOF
CREATE USER $DB_ICAT_USERNAME IDENTIFIED BY '$DB_ICAT_PASSWORD';
CREATE DATABASE $DB_ICAT_USERNAME;
GRANT ALL ON $DB_ICAT_USERNAME.* to '$DB_ICAT_USERNAME'@'%';

CREATE USER $DB_ICATUSER_USERNAME IDENTIFIED BY '$DB_ICATUSER_PASSWORD';
CREATE DATABASE $DB_ICATUSER_USERNAME;
GRANT ALL ON $DB_ICATUSER_USERNAME.* to '$DB_ICATUSER_USERNAME'@'%';

FLUSH PRIVILEGES;
EOF

#
# - the end -
#