#!/usr/bin/env python
from setup_utils import *
import os

# authn_ldap

actions, options, arg = getActions()
props = actions.getGlassfish("authn_ldap-setup.properties", ["glassfish", "port"])

prop_name = "authn_ldap.properties"
prop_list = []

if arg == "CONFIGURE":
    actions.configure(prop_name, prop_list)
    actions.setConfigured()
    
elif arg == "INSTALL":
    
    actions.checkConfigured()
           
    icatProperties = actions.getProperties(prop_name, prop_list)       
           
    actions.installFile(prop_name)
    
    try:
        
        app = actions.getAppName("authn_ldap.ear")
        if app: actions.asadmin("undeploy " + app) 
        app = actions.getAppName("authn_ldap")
        if app: actions.asadmin("undeploy " + app)
           
        actions.deploy("authn_ldap-*.war")
                    
    except Exception, e:
        abort(str(e))
               
else:  # UNINSTALL
    
    actions.removeFile(prop_name)
    
    try:
        app = actions.getAppName("authn_ldap")
        if app: actions.asadmin("undeploy " + app)
    except Exception, e:
        abort(str(e))       
    
            
    
