REM This is the upgrade script for the icat3 schema to include DOI (Digital Object Identifier)
REM 
PROMPT
PROMPT I C A T    U P G R A D E   I N S T A L L
PROMPT
PROMPT This script will upgrade existing icat3 schema to include additional  
PROMPT tables for DOI (Digital Object Identifiers
PROMPT

REM undefine database_name
REM undefine icat_username
REM undefine icat_password
REM PROMPT
REM PROMPT
REM ACCEPT icat_username CHAR prompt       'Enter ICAT schema name      : '
REM ACCEPT icat_password CHAR prompt           'Enter icat password       : '

PROMPT Connecting ....
connect icat_username/&icat_password@&database_name

PROMPT Creating Tables 

CREATE TABLE DOI 
(
  ID NUMBER NOT NULL 
, SERVER_ID NUMBER NOT NULL 
, NAME VARCHAR2(255) 
, DCOL VARCHAR2(31) 
, CONSTRAINT DOI_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE DOI_SERVER 
(
  ID NUMBER NOT NULL 
, SERVER_NAME VARCHAR2(255) 
, SERVER_URL VARCHAR2(255) 
, CONSTRAINT DOI_SERVER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE INVESTIGATION_DOI 
(
  ID NUMBER NOT NULL 
, INVESTIGATION_ID NUMBER(38, 0) NOT NULL 
, CONSTRAINT INVESTIGATION_DOI_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE DATASET_DOI 
(
  ID NUMBER NOT NULL 
, DATASET_ID NUMBER(38, 0) NOT NULL 
, CONSTRAINT DATASET_DOI_PK PRIMARY KEY 

  (
    ID 
  )
  ENABLE 
);

CREATE TABLE DATAFILE_DOI 
(
  ID NUMBER NOT NULL 
, DATAFILE_ID NUMBER(38, 0) 
, CONSTRAINT DATAFILE_DOI_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE DOI
ADD CONSTRAINT DOI_UK1 UNIQUE 
(
  SERVER_ID 
, NAME 
)
ENABLE;

ALTER TABLE DOI
ADD CONSTRAINT DOI_DOI_SERVER_FK1 FOREIGN KEY
(
  SERVER_ID 
)
REFERENCES DOI_SERVER
(
  ID 
)
ENABLE;

ALTER TABLE INVESTIGATION_DOI
ADD CONSTRAINT INVESTIGATION_DOI_INVESTI_FK1 FOREIGN KEY
(
  INVESTIGATION_ID 
)
REFERENCES INVESTIGATION
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DATASET_DOI
ADD CONSTRAINT DATASET_DOI_DATASET_FK1 FOREIGN KEY
(
  DATASET_ID 
)
REFERENCES DATASET
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE DATAFILE_DOI
ADD CONSTRAINT DATAFILE_DOI_DATAFILE_FK1 FOREIGN KEY
(
  DATAFILE_ID 
)
REFERENCES DATAFILE
(
  ID 
)
ON DELETE CASCADE ENABLE;

CREATE SEQUENCE doi_id_seq START WITH 5000 NOCACHE;
CREATE SEQUENCE doi_server_id_seq START WITH 1 NOCACHE;

PROMPT Installation Complete
exit;

